version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      timeout: 180
      runas: root
