version: 0.2
 
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - export AWS_ACCOUNT_ID=089358501446
      - export AWS_REGION=ap-south-1
      - export REPOSITORY_NAME=satic-websites
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest
      - aws ecr get-login-password --region $AWS_REGION | aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 089358501446.dkr.ecr.ap-south-1.amazonaws.com
 
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_URI .
 
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $IMAGE_URI
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"app","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json
 
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - imagedefinitions.json
